version: '2.1'

services:
  users:
    build: users-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy 

  events:
    build: events-service
    mem_limit: 350m
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy 
 
  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: authorization-server
    mem_limit: 350m
    ports:
      - "9999:9999"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 20s
      timeout: 5s
      retries: 10

